force-app/main/default/objects/Case/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TripID__c.field-meta.xml
<CustomField>
    <fullName>TripID__c</fullName>
    <label>TripID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>T#{00000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseManager.cls
public with sharing class CaseManager {
    public static void connectAccountToCaseByTripId(List<Case> cases) {
        Set<String> tripIds = new Set<String>();
        for (Case incomingCase : cases) {
            if (incomingCase.TripID__c != null && incomingCase.AccountId == null) {
                tripIds.add(incomingCase.TripID__c);
            }
        }
        if (!tripIds.isEmpty()) {
            List<Trip__c> trips = [SELECT Id, Account__c, Name FROM Trip__c WHERE Name IN :tripIds];
            Map<String, Trip__c> mTripsNames = new Map<String, Trip__c>();
            for (Trip__c trip : trips) {
                mTripsNames.put(trip.Name, trip);
            }
            for (Case incomingCase : cases) {
                if (incomingCase.TripID__c != null && incomingCase.AccountId == null) {
                    Trip__c theTrip = mTripsNames.get(incomingCase.TripID__c.toUpperCase());
                    Id accountId = theTrip.Account__c;
                    incomingCase.AccountId = accountId;
                    incomingCase.Trip__c = theTrip.Id;
                    System.debug('connectAccountToCaseByTripId... updating case... ' + incomingCase);
                }
            }
        }
    }
}